### ISSUE TITLE
Rename Events into hackathons inside the app

### ISSUE THREAD

**Issue by chamathpali** [SurfEdge/hackathons-lk-app#14]

**Comment by amanthaIsuru** [comment]
Issue is not clear. I have added the dummy data :P

**Comment by chamathpali** [comment]
inside the app it says "Upcoming Events" -> it should be Hackathons.. replace events with hackathons

**Comment by amanthaIsuru** [comment]
Done

**Comment by chamathpali** [comment]
wheres the PR or commit? :P

**Comment by chamathpali** [comment]
wheres the PR or commit? :P

**Comment by chamathpali** [comment]
wheres the PR or commit? :P
