### ISSUE TITLE
Initialize header and footer

### ISSUE THREAD

**Issue by chamathpali** [SurfEdge/hackathons-lk-app#4]
Footer need to have "Upcoming", "Ended", "About", "Contact",

Header just the name of the app "Events Listing"

**Comment by amanthaIsuru** [comment]
Initialized and modified the application.

**Comment by chamathpali** [comment]
please map the title of the header with the page name

**Comment by amanthaIsuru** [comment]
Done

**Comment by chamathpali** [comment]
#13
