### ISSUE TITLE
Edit Readme, Add screenshots of the initial app structure

### ISSUE THREAD

**Issue by chamathpali** [SurfEdge/hackathons-lk-app#5]

**Comment by sanchit-bansal** [comment]
Can you assign this to me ? 

Also what sort of a application is this ? , how do I run it on ubuntu ?

**Comment by chamathpali** [comment]
this is an ionic mobile hybrid  application. http://ionic.io/
this is for listing events and countdown to them. and show upcoming, ended events

**Comment by 24paras** [comment]
Hi! I would like to edit the README.md file. Can you tell me some details which you would like the file to have?

**Comment by chamathpali** [comment]
#
