### ISSUE TITLE
Add badge to show total count of events in the list 

### ISSUE THREAD

**Issue by chamathpali** [SurfEdge/hackathons-lk-app#8]
add a count label in the top of the list to show how many events (cards are there)

ex: 
10 Upcoming Events
2 Ended Events

**Comment by maxervo** [comment]
Hi, do you want the count label to be in a particular style? :)

**Comment by chamathpali** [comment]
anystyle is fine

**Comment by chamathpali** [comment]
@rstoke check this issue : #12 if possible

**Comment by amanthaIsuru** [comment]
Done
